export default [
  {value: 1, label: 'Weight Loss'},
  {value: 2, label: 'Low Carb'},
  {value: 3, label: 'Heart Healthy'},
  {value: 4, label: 'Low Cholesterol'},
  {value: 5, label: 'On The Go'},
  {value: 6, label: 'Energy Booster'},
  {value: 7, label: 'Teen Scene'},
  {value: 8, label: 'Healthy Aging'},
  {value: 9, label: 'Mature Women'},
  {value: 10, label: 'Lean Body Builder'},
  {value: 11, label: 'Mass Builder'},
  {value: 12, label: 'Performance Training'},
  {value: 13, label: 'Low (am) to High (pm) Glycemic'},
  {value: 14, label: 'High (am) to Low (am) Glycemic'},
  {value: 15, label: 'Low Glycemic'},
  {value: 16, label: 'Vegetarian'},
  {value: 18, label: 'Wheat Free'},
  {value: 19, label: 'Breast Cancer'},
  {value: 20, label: 'Stable Blood Sugar'},
  {value: 21, label: 'Heart Disease'},
  {value: 22, label: 'Osteoporosis (Bone Health)'},
  {value: 23, label: 'Stroke Prevention (DASH)'},
  {value: 24, label: 'Cancer Prevention'},
  {value: 25, label: 'Low Carb American'},
  {value: 26, label: 'Low Carb Mexican'},
  {value: 27, label: 'Low Carb Italian'},
  {value: 28, label: 'Low Carb Fast Food'},
  {value: 29, label: 'Kosher'},
  {value: 30, label: 'Organic Low Fat'},
  {value: 31, label: 'Organic Low Carb'},
  {value: 32, label: 'Gluten Free'},
  {value: 33, label: 'Lactose Intolerant'},
  {value: 40, label: 'North Beach Diet Phase I'},
  {value: 157, label: 'Asian Explosion'},
  {value: 158, label: 'Mediterranean'},
  {value: 159, label: 'Healthy Soy'},
  {value: 253, label: 'Bariatric Low Calories Low Carb'},
  {value: 254, label: 'Bariatric Low Calorie Low Glycemic'},
  {value: 255, label: 'Bariatric Lap Band Post Op'},
  {value: 269, label: 'High Fiber'},
  {value: 270, label: 'North Beach Diet Phase II'},
  {value: 285, label: '21 day Jump Start Detox Meat for Men'},
  {value: 286, label: '21 day Jump Start Detox Meat for Women'},
  {value: 287, label: '21 Day Jump  Start Detox Veggie for Men'},
  {value: 288, label: '21 Day Jump Start Detox Veggie for Women'},
  {value: 290, label: '21 Day Jump Start Detox Fruit for Women'},
  {value: 291, label: 'Detox with Fruit for Men'},
  {value: 292, label: 'Detox with Fruit for Women'},
  {value: 293, label: 'Detox with Veggie for Men'},
  {value: 294, label: 'Detox with Veggie for Women'},
  {value: 295, label: 'Detox with Meat for Men'},
  {value: 296, label: 'Detox with Meat for Women'},
  {value: 652, label: 'Develop Healthy Eating Habits (9‐13 years)'},
  {value: 653, label: 'Getting a Healthy Start (2‐3 years)'},
  {value: 654, label: 'Growing Up With Healthy Habits (4‐8 years)'},
  {value: 655, label: 'Healthy Teen Years (14‐18 years)'},
  {value: 656, label: 'Childhood Obesity Low Cholesterol'},
  {value: 851, label: 'Allergy Series ‐ Chicken Egg'},
  {value: 852, label: 'Allergy Series ‐ Cow Milk'},
  {value: 853, label: 'Allergy Series ‐ Peanut'},
  {value: 854, label: 'Allergy Series ‐ Pinenut'},
  {value: 855, label: 'Allergy Series ‐ Shellfish'},
  {value: 907, label: 'Paleo (Caveman)'},
  {value: 1163, label: 'Breast Feeding'},
  {value: 1164, label: 'Prenatal'},
  {value: 1166, label: 'Post Pregnancy Weight Loss'},
]
